version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    ECR_REPO: 127145910156.dkr.ecr.ap-south-1.amazonaws.com/docker/nodejs

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo IMAGE_TAG=$IMAGE_TAG

  build:
    commands:
      - echo Building Docker image...
      - docker build -t my-app:$IMAGE_TAG .
      - docker tag my-app:$IMAGE_TAG $ECR_REPO:$IMAGE_TAG
      - docker tag my-app:$IMAGE_TAG $ECR_REPO:latest
      - docker push $ECR_REPO:latest

  post_build:
    commands:
      - echo Creating imagedefinitions.json...
      - printf '[{"name":"nodejs","imageUri":"%s"}]' "$ECR_REPO:$IMAGE_TAG" > imagedefinitions.json

artifacts:
  files:
    - appspec.yml
    - scripts/start.sh
    - imagedefinitions.json
